
---
spring:
  jpa:
    generate-ddl: true

# turn off the security on the actuator end points as this is a demo app
management:
  security:
    enabled: true
    roles: SUPERUSER

security:
  user:
    name: admin

endpoints:
  hypermedia:
    enabled: true

nmt:
  metrics:
    enabled: ${nmt-enabled:false}


logging:
  level:
    root: INFO
